### ISSUE TITLE
\CacheProvider::initialize() should not be abstract

### ISSUE THREAD

**Issue by manfredjb** [atrauzzi/laravel-doctrine#76] opened 2015-05-05 04:46 UTC
Hello atrauzzi,
Today I update the project via composer. After a the command ran without problems and refreshing doctrine config file, the application is displaying this error message:
 
```php
ErrorException in CacheProvider.php line 32: Static function Atrauzzi\LaravelDoctrine\CacheProvider\CacheProvider::initialize() should not be abstract
```

![Imgur](http://i.imgur.com/zh2Awxv.png)

I want to that line and the IDE is telling me that effectively the `initialize() should not be abstract`:
![Doctrine error](http://i.imgur.com/A7puifF.png)

**Comment by mbbender** [comment] 2015-05-05 11:39
I actually did this refactoring but didn't have much to go on with testing. If you could share your authentication driver I'd be happy to fix the issue.

**Comment by atrauzzi** [comment] 2015-05-05 11:40
Thanks @mbbender :)

**Comment by mbbender** [comment] 2015-05-05 13:27
@manfredjb What version of PHP are you using? I found a few issues when testing the cache providers initialization which I just submitted a pull request for. You can see if this solves your problem, but I didn't specifically see the issue of abstract static being an issue. It uses late static binding so should be no problem that it is abstract static method.

**Comment by atrauzzi** [comment] 2015-05-05 13:56
Merged the test.

**Comment by manfredjb** [comment] 2015-05-05 17:11
@mbbender, I am on PHP 5.5.23, also, the production machine is running over PHP 5.5.20. I will update the package right now.

**Comment by manfredjb** [comment] 2015-05-05 17:30
Well, after test the changes in two machines, the error persist with a little difference:

```php
ErrorException in CacheProvider.php line 35: Static function Atrauzzi\LaravelDoctrine\CacheProvider\CacheProvider::initialize() should not be abstract
```

**Comment by mbbender** [comment] 2015-05-05 20:30
Hum, I'm not able to reproduce this issue. I think it may be related to error reporting settings. However, I'm guessing it's not good practice to implement that way if it is being reported as an error in some settings. I attempted to remove the abstract static function. I just sent over the pull request so you can try to merge it in yourself or what until @atrauzzi   merges it in.

**Comment by manfredjb** [comment] 2015-05-05 20:40
@mbbender, I can confirm to you that your last commit fix the issue!  Let's wait to @atrauzzi review to merge.

**Closed** 2015-05-05 20:43 UTC
